fix: no quotes required in default value expansion
patch for ed334e807395c517e4b09c537777fbb57b88a7bd , oops...

Streamlink said:
  error: The specified stream(s) ''best'' could not be found.
         Available streams: 240p (worst), 360p, 480p, 720p, 1080p (best)

This story told us:
  don't make untested changes that are not mentioned in commit message.